"use client";

import { useEffect, useRef, useState } from "react";
import { CsvUploadCard } from "@/components/csv-upload-card";
import { ModalDialog } from "@/components/modal-dialog";
import { TeacherShell } from "@/components/teacher-shell";
import { useToast } from "@/components/toast-provider";
import { applyNormalImport, getAdminYears, previewNormalImport, type NormalImportApplyResponse, type NormalImportKind, type NormalImportPreviewResponse } from "@/lib/admin-api";
import { GradeApiError } from "@/lib/grade-api";
import { importKindLabels, importFingerprint, safeCredentialCsv, sameImportSnapshot, snapshotIsReady, type ImportSnapshot } from "@/lib/import-state";
import { shouldAllowNavigation, shouldRestoreHistoryOnPopstate } from "@/lib/navigation-guard";

type Confirmed = { snapshot: ImportSnapshot; preview: NormalImportPreviewResponse; idempotencyKey: string | null };
const kinds: NormalImportKind[] = ["students", "teachers", "staff", "subjects"];

export function AdminImportPage() {
  const { showError, showSuccess } = useToast();
  const [mobile, setMobile] = useState(true); const [year, setYear] = useState<number | null>(null); const [kind, setKind] = useState<NormalImportKind>("students"); const [gradeLevel, setGradeLevel] = useState<1 | 2 | 3>(1); const [csv, setCsv] = useState(""); const [fileName, setFileName] = useState<string | null>(null); const [reading, setReading] = useState(false); const [saving, setSaving] = useState(false); const [confirmed, setConfirmed] = useState<Confirmed | null>(null); const [credentials, setCredentials] = useState<NormalImportApplyResponse["credentials"]>([]); const [applied, setApplied] = useState<NormalImportApplyResponse | null>(null); const [error, setError] = useState<string | null>(null);
  const readGeneration = useRef(0); const previewGeneration = useRef(0); const controller = useRef<AbortController | null>(null); const savingRef = useRef(false); const confirmedRef = useRef<Confirmed | null>(null);
  const snapshot = (): ImportSnapshot | null => year === null ? null : { academicYear: year, kind, csv, ...(kind === "subjects" ? { gradeLevel } : {}) };
  const busy = reading || saving; const current = snapshot(); const dirty = Boolean(csv || credentials.length); const navGuard = () => shouldAllowNavigation(dirty, () => window.confirm("選択したCSVまたは一時パスワードが失われます。移動しますか？"), busy);
  const invalidate = () => { previewGeneration.current += 1; controller.current?.abort(); confirmedRef.current = null; setConfirmed(null); setApplied(null); setError(null); };
  useEffect(() => { const media = window.matchMedia("(max-width: 640px)"); const sync = () => setMobile(media.matches); sync(); media.addEventListener("change", sync); return () => media.removeEventListener("change", sync); }, []);
  useEffect(() => { let active = true; void getAdminYears().then((result) => { const selected = result.years.find((item) => item.isCurrent)?.year ?? null; if (active) setYear(selected); }).catch(() => active && setError("現在年度を取得できませんでした。")); return () => { active = false; }; }, []);
  useEffect(() => () => controller.current?.abort(), []);
  useEffect(() => { const handler = (event: BeforeUnloadEvent) => { if (dirty || busy) { event.preventDefault(); event.returnValue = ""; } }; window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty, busy]);
  useEffect(() => { const handler = () => { if (shouldRestoreHistoryOnPopstate(dirty, () => window.confirm("選択したCSVまたは一時パスワードが失われます。移動しますか？"), busy)) window.history.go(1); }; window.addEventListener("popstate", handler); return () => window.removeEventListener("popstate", handler); }, [dirty, busy]);
  async function read(file: File | undefined) { if (!file || busy) return; const generation = ++readGeneration.current; invalidate(); setReading(true); try { const value = await file.text(); if (generation !== readGeneration.current) return; if (value.includes("\uFFFD")) throw new Error("UTF-8形式のCSVを選択してください。"); setCsv(value); setFileName(file.name); } catch (cause) { if (generation === readGeneration.current) setError(cause instanceof Error ? cause.message : "CSVを読み込めませんでした。"); } finally { if (generation === readGeneration.current) setReading(false); } }
  const changeKind = (next: NormalImportKind) => { if (busy) return; setKind(next); setCsv(""); setFileName(null); invalidate(); };
  async function preview() { const fixed = snapshot(); if (!fixed || mobile || busy || !snapshotIsReady(fixed)) return; const generation = ++previewGeneration.current; controller.current?.abort(); const next = new AbortController(); controller.current = next; savingRef.current = true; setSaving(true); setError(null); try { const result = await previewNormalImport(fixed, next.signal); const latest = snapshot(); if (generation === previewGeneration.current && latest && sameImportSnapshot(fixed, latest)) { const nextConfirmed = { snapshot: fixed, preview: result, idempotencyKey: null }; confirmedRef.current = nextConfirmed; setConfirmed(nextConfirmed); } } catch (cause) { if (generation === previewGeneration.current && !(cause instanceof DOMException && cause.name === "AbortError")) showError(cause instanceof GradeApiError ? cause.message : "CSVの確認に失敗しました。"); } finally { if (generation === previewGeneration.current) { savingRef.current = false; setSaving(false); } } }
  async function apply() { const fixed = confirmedRef.current; const latest = snapshot(); if (!fixed || !latest || mobile || busy || applied || !sameImportSnapshot(fixed.snapshot, latest)) { showError("入力内容が変わりました。もう一度確認してください。"); return; } if (fixed.preview.errors.length || !fixed.preview.token) return; const idempotencyKey = fixed.idempotencyKey ?? crypto.randomUUID().replaceAll("-", ""); const retry = { ...fixed, idempotencyKey }; confirmedRef.current = retry; setConfirmed(retry); savingRef.current = true; setSaving(true); setError(null); try { const result = await applyNormalImport({ token: fixed.preview.token, idempotencyKey }); setCredentials(result.credentials); setApplied(result); setConfirmed(null); showSuccess("反映しました。再送は行いません。"); } catch (cause) { showError(cause instanceof GradeApiError ? cause.message : "反映に失敗しました。入力内容は保持されています。"); } finally { savingRef.current = false; setSaving(false); } }
  const download = () => { const blob = new Blob([safeCredentialCsv(credentials)], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "一時パスワード一覧.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const closeCredentials = () => { setCredentials([]); setCsv(""); setFileName(null); invalidate(); };
  const count = confirmed ? confirmed.preview.counts.students + confirmed.preview.counts.teachers + confirmed.preview.counts.staff + confirmed.preview.counts.subjects[1] + confirmed.preview.counts.subjects[2] + confirmed.preview.counts.subjects[3] : 0;
  return <TeacherShell variant="admin" navigationGuard={navGuard}><header className="pageHeader"><p className="sectionEyebrow">専任職員</p><h1>通常CSV取込</h1><p>現在年度（{year ?? "確認中"}年度）へ、1種類のCSVを確認してから反映します。学生CSVに載っていない学生は変更しません。</p></header>{mobile ? <p className="readOnlyNotice">スマートフォンでは閲覧のみです。CSV取込はパソコンで行ってください。</p> : null}{error ? <p className="formError" role="alert">{error}</p> : null}<section className="masterCard"><div className="masterForm"><label>CSVの種類<select value={kind} disabled={mobile || busy || Boolean(applied)} onChange={(event) => changeKind(event.target.value as NormalImportKind)}>{kinds.map((item) => <option key={item} value={item}>{importKindLabels[item]}</option>)}</select></label>{kind === "subjects" ? <label>対象学年<select value={gradeLevel} disabled={mobile || busy || Boolean(applied)} onChange={(event) => { setGradeLevel(event.target.value === "2" ? 2 : event.target.value === "3" ? 3 : 1); invalidate(); }}><option value={1}>1年</option><option value={2}>2年</option><option value={3}>3年</option></select></label> : null}<CsvUploadCard label="CSVファイル" disabled={mobile || busy || Boolean(applied) || year === null} loaded={Boolean(csv)} loading={reading} selectedFileName={fileName} onInvalidSelection={() => setError("CSVファイルは1件のみ選択してください。")} onSelectFile={(file) => void read(file)} /></div><button className="primaryAction compactAction" type="button" disabled={mobile || busy || Boolean(applied) || !current || !snapshotIsReady(current)} onClick={() => void preview()}>{saving ? "確認中…" : "内容を確認する"}</button></section><ModalDialog open={Boolean(confirmed)} title="CSVの内容を確認" dismissible={!busy} onRequestClose={() => { if (!busy) { setConfirmed(null); confirmedRef.current = null; } }}>{confirmed ? <><p>{importKindLabels[confirmed.snapshot.kind]}: {count}件</p>{confirmed.preview.errors.length ? <ul>{confirmed.preview.errors.map((item, index) => <li key={`${item.file}-${index}`}>{item.file} {item.row ? `${item.row}行目` : ""}：{item.field} {item.reason}</li>)}</ul> : <p className="formSuccess">問題ありません。反映できます。</p>}<div className="appDialogActions"><button className="secondaryAction compactAction" type="button" disabled={busy} onClick={() => { setConfirmed(null); confirmedRef.current = null; }}>キャンセル</button><button className="primaryAction compactAction" type="button" disabled={mobile || busy || Boolean(confirmed.preview.errors.length) || !current || importFingerprint(confirmed.snapshot) !== importFingerprint(current)} onClick={() => void apply()}>{saving ? "反映中…" : "反映する"}</button></div></> : null}</ModalDialog><ModalDialog open={credentials.length > 0} title="一時パスワードを保存" dismissible={false} onRequestClose={() => {}}><p>この画面を閉じると再表示できません。安全な場所に保存してください。</p><div className="appDialogActions"><button className="primaryAction compactAction" type="button" onClick={download}>一時パスワードCSVを保存</button><button className="secondaryAction compactAction" type="button" onClick={closeCredentials}>保存済みとして閉じる</button></div></ModalDialog></TeacherShell>;
}
