import { access, mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "bun:test";

import {
  CliError,
  buildCompensationSql,
  buildCreateAdminSql,
  buildWranglerReadCommand,
  buildWranglerWriteCommand,
  createAdmin,
  executeReadSql,
  executeWriteSql,
  parseArguments,
  quoteSql,
} from "./create-admin";

const temporaryDirectories: string[] = [];
const emptyResponse = JSON.stringify([{ results: [] }]);

afterEach(async () => {
  await Promise.all(
    temporaryDirectories.splice(0).map((directory) =>
      rm(directory, { recursive: true, force: true }),
    ),
  );
});

async function temporaryRoot() {
  const directory = await mkdtemp(join(tmpdir(), "grade-management-admin-test-"));
  temporaryDirectories.push(directory);
  return directory;
}

describe("admin:create argument parsing", () => {
  it("defaults to local D1 and normalizes the input", () => {
    expect(parseArguments(["--name", " 専任 職員 ", "--email", "STAFF@EXAMPLE.COM"])).toEqual({
      kind: "create",
      name: "専任 職員",
      email: "staff@example.com",
      target: "local",
      yes: false,
    });
  });

  it("requires an explicit remote target for --yes", () => {
    expect(parseArguments(["--name", "職員", "--email", "staff@example.com", "--remote", "--yes"])).toMatchObject({
      target: "remote",
      yes: true,
    });
    expect(() => parseArguments(["--name", "職員", "--email", "staff@example.com", "--yes"])).toThrow(
      CliError,
    );
  });

  it("rejects passwords and unknown options before any database operation", () => {
    expect(() => parseArguments(["--name", "職員", "--email", "staff@example.com", "--password", "secret"])).toThrow(
      "パスワードはコマンドライン引数で指定できません",
    );
    expect(() => parseArguments(["--name", "職員", "--email", "staff@example.com", "--oops"])).toThrow(
      "不明なオプション",
    );
  });
});

describe("admin:create SQL and Wrangler command", () => {
  it("escapes SQL literals and inserts the required Better Auth values without a transaction wrapper", () => {
    const payload = {
      id: "user-id",
      accountId: "account-id",
      name: "O'Reilly'); DELETE FROM user; --",
      email: "staff@example.com",
      passwordHash: "hash'value",
    };
    const sql = buildCreateAdminSql(payload);

    expect(quoteSql(payload.name)).toBe("'O''Reilly''); DELETE FROM user; --'");
    expect(sql).toContain("'admin', 'active', 1");
    expect(sql).toContain("'credential'");
    expect(sql).toContain("'user-id'");
    expect(sql).toContain("'hash''value'");
    expect(sql).not.toContain("BEGIN");
    expect(sql).not.toContain("COMMIT");
  });

  it("builds argv-array commands for the selected D1 target", () => {
    const local = buildWranglerWriteCommand("/tmp/admin.sql", "local");
    const remote = buildWranglerWriteCommand("/tmp/admin.sql", "remote");

    expect(local).toContain("--local");
    expect(local).not.toContain("--remote");
    expect(remote).toContain("--remote");
    expect(remote).not.toContain("--local");
    expect(local).toContain("--file");
    expect(local[local.indexOf("--file") + 1]).toBe("/tmp/admin.sql");

    const readLocal = buildWranglerReadCommand("SELECT 1;", "local");
    const readRemote = buildWranglerReadCommand("SELECT 1;", "remote");
    expect(readLocal).toContain("--command");
    expect(readLocal).not.toContain("--file");
    expect(readLocal).toContain("--local");
    expect(readRemote).toContain("--remote");
  });

  it("limits compensation to the IDs and exact user fields generated by this invocation", () => {
    const sql = buildCompensationSql({
      id: "new-user-id",
      accountId: "new-account-id",
      name: "新規 職員",
      email: "new@example.com",
      passwordHash: "hash",
    });

    expect(sql).toContain('WHERE "id" = \'new-account-id\'');
    expect(sql).toContain('AND "account_id" = \'new-user-id\'');
    expect(sql).toContain("AND \"provider_id\" = 'credential'");
    expect(sql).toContain('AND "user_id" = \'new-user-id\'');
    expect(sql).toContain('WHERE "id" = \'new-user-id\'');
    expect(sql).toContain('AND "name" = \'新規 職員\'');
    expect(sql).toContain('AND "email" = \'new@example.com\'');
    expect(sql).not.toContain('WHERE "email" =');
  });
});

describe("admin:create execution safeguards", () => {
  it("uses a 0600 temporary SQL file and removes it after the Wrangler command", async () => {
    const root = await temporaryRoot();
    let sqlFile = "";
    let capturedSql = "";

    await expect(
      executeWriteSql("SELECT 1;\n", "local", {
        temporaryRoot: root,
        runCommand: async (command) => {
          sqlFile = command[command.indexOf("--file") + 1] ?? "";
          capturedSql = await readFile(sqlFile, "utf8");
          expect((await stat(sqlFile)).mode & 0o777).toBe(0o600);
          return { exitCode: 0, stdout: emptyResponse, stderr: "" };
        },
      }),
    ).resolves.toBe(emptyResponse);

    expect(capturedSql).toBe("SELECT 1;\n");
    await expect(access(sqlFile)).rejects.toThrow();
  });

  it("reads remote SELECT rows through --command and never places the password hash in argv", async () => {
    const result = await executeReadSql("SELECT 'new-user-id' AS id;", "remote", {
      runCommand: async (command) => {
        expect(command).toContain("--command");
        expect(command).not.toContain("--file");
        expect(command).toContain("--remote");
        expect(command.join(" ")).not.toContain("safe-password-hash");
        return {
          exitCode: 0,
          stdout: JSON.stringify([{ results: [{ id: "new-user-id" }] }]),
          stderr: "",
        };
      },
    });
    expect(result).toEqual([{ id: "new-user-id" }]);
  });

  it("never displays the generated password when creation fails, and removes only its generated records", async () => {
    const root = await temporaryRoot();
    const password = "NeverPrintThisPassword";
    const executedSql: string[] = [];
    const commands: string[][] = [];

    await expect(
      createAdmin(
        { name: "専任職員", email: "staff@example.com", target: "local" },
        {
          temporaryRoot: root,
          generateId: (() => {
            const ids = ["new-user-id", "new-account-id"];
            return () => ids.shift() ?? "unexpected-id";
          })(),
          generatePassword: () => password,
          hash: async () => "safe-password-hash",
          runCommand: async (command) => {
            commands.push(command);
            if (command.includes("--command")) {
              return { exitCode: 0, stdout: emptyResponse, stderr: "" };
            }
            const sqlFile = command[command.indexOf("--file") + 1] ?? "";
            const sql = await readFile(sqlFile, "utf8");
            executedSql.push(sql);
            if (sql.includes('INSERT INTO "user"')) {
              return { exitCode: 1, stdout: "", stderr: "write failed" };
            }
            return { exitCode: 0, stdout: emptyResponse, stderr: "" };
          },
        },
      ),
    ).rejects.toThrow("専任職員アカウントを作成できませんでした");

    const allOutput = executedSql.join("\n");
    expect(allOutput).not.toContain(password);
    expect(commands.flat().join(" ")).not.toContain(password);
    expect(commands.flat().join(" ")).not.toContain("safe-password-hash");
    expect(allOutput).toContain('WHERE "id" = \'new-account-id\'');
    expect(allOutput).toContain('AND "user_id" = \'new-user-id\'');
    expect(allOutput).toContain('DELETE FROM "user"');
  });

  it("returns the password only after the inserted user and credential account are verified", async () => {
    const root = await temporaryRoot();
    const commands: string[][] = [];

    const created = await createAdmin(
      { name: "専任職員", email: "staff@example.com", target: "remote" },
      {
        temporaryRoot: root,
        generateId: (() => {
          const ids = ["new-user-id", "new-account-id"];
          return () => ids.shift() ?? "unexpected-id";
        })(),
        generatePassword: () => "ShownOnlyAfterVerification",
        hash: async () => "safe-password-hash",
        runCommand: async (command) => {
          commands.push(command);
          const sql = command.includes("--command")
            ? (command[command.indexOf("--command") + 1] ?? "")
            : await readFile(command[command.indexOf("--file") + 1] ?? "", "utf8");
          if (sql.includes('LEFT JOIN "account"')) {
            return {
              exitCode: 0,
              stdout: JSON.stringify([
                {
                  results: [
                    {
                      id: "new-user-id",
                      name: "専任職員",
                      email: "staff@example.com",
                      role: "admin",
                      status: "active",
                      must_change_password: 1,
                      account_id: "new-account-id",
                      provider_account_id: "new-user-id",
                      provider_id: "credential",
                      user_id: "new-user-id",
                      password: "safe-password-hash",
                    },
                  ],
                },
              ]),
              stderr: "",
            };
          }
          return {
            exitCode: 0,
            stdout: command.includes("--file")
              ? JSON.stringify({ results: [{ success: true, messages: [], result: [{ results: [] }] }] })
              : emptyResponse,
            stderr: "",
          };
        },
      },
    );

    expect(created).toEqual({
      id: "new-user-id",
      email: "staff@example.com",
      temporaryPassword: "ShownOnlyAfterVerification",
      target: "remote",
    });
    expect(commands.every((command) => command.includes("--remote"))).toBe(true);
    expect(commands.filter((command) => command.includes("--file"))).toHaveLength(1);
    expect(commands.filter((command) => command.includes("--command")).length).toBeGreaterThanOrEqual(3);
    expect(commands.flat().join(" ")).not.toContain("staff@example.com");
    expect(commands.flat().join(" ")).not.toContain("safe-password-hash");
  });

  it("reports a duplicate email from the write result without deleting an existing account", async () => {
    const root = await temporaryRoot();
    const executedSql: string[] = [];

    await expect(
      createAdmin(
        { name: "専任職員", email: "staff@example.com", target: "remote" },
        {
          temporaryRoot: root,
          generateId: (() => {
            const ids = ["new-user-id", "new-account-id"];
            return () => ids.shift() ?? "unexpected-id";
          })(),
          runCommand: async (command) => {
            if (command.includes("--command")) {
              return { exitCode: 0, stdout: emptyResponse, stderr: "" };
            }
            const sql = await readFile(command[command.indexOf("--file") + 1] ?? "", "utf8");
            executedSql.push(sql);
            if (sql.includes('INSERT INTO "user"')) {
              return { exitCode: 1, stdout: "", stderr: "UNIQUE constraint failed: user.email" };
            }
            return { exitCode: 0, stdout: emptyResponse, stderr: "" };
          },
        },
      ),
    ).rejects.toThrow("既存のアカウント");

    expect(executedSql).toHaveLength(2);
    expect(executedSql[0]).toContain('INSERT INTO "user"');
    expect(executedSql[1]).toContain('WHERE "id" = \'new-account-id\'');
    expect(executedSql[1]).toContain('WHERE "id" = \'new-user-id\'');
    expect(executedSql[1]).not.toContain('WHERE "email" =');
  });
});
