import { describe, expect, it } from "bun:test";
import { createApp } from "../app";
import type { AuthSession } from "../authorization";
import { unavailableGradeService } from "../grade/service";
import { unavailableAdminMasterService } from "./service";
import { unavailableAuditService } from "./audit";
import { PdfExportUnavailableError } from "./grade-export";

const admin: AuthSession = { session: { id: "s", token: "t", expiresAt: new Date("2027-01-01") }, user: { id: "admin", role: "admin", status: "active", mustChangePassword: false } };
const gradeExportService = { preview: async () => ({ token: "snapshot-token-0123456789", rowCount: 1, academicYear: 2027, years: [2027], scope: "year_all_students" as const, format: "csv" as const }), download: async () => ({ csv: "\uFEFFa\r\n", filename: "成績一覧_2027年度.csv", rowCount: 1 }), downloadPdf: async () => ({ pdf: Uint8Array.from([37, 80, 68, 70]).buffer, filename: "成績一覧_2027年度.pdf", rowCount: 1 }) };
const app = (session: AuthSession | null = admin, service = gradeExportService) => createApp({ authHandler: () => new Response(null, { status: 500 }), readSession: async () => session, gradeService: unavailableGradeService, adminMasterService: unavailableAdminMasterService, auditService: unavailableAuditService, gradeExportService: service });
describe("grade export routes", () => {
  it("requires an admin and validates a required preview format", async () => { const teacher = { ...admin, user: { ...admin.user, role: "teacher" as const } }; expect((await app(teacher).request("/api/admin/grade-export/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope: "year_all_students", format: "csv" }) })).status).toBe(403); expect((await app(teacher).request("/api/admin/grade-export/pdf?token=snapshot-token-0123456789")).status).toBe(403); expect((await app().request("/api/admin/grade-export/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope: "year_all_students" }) })).status).toBe(400); expect((await app().request("/api/admin/grade-export/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope: "invalid", format: "csv" }) })).status).toBe(400); });
  it("returns download headers only after a tokenized preview", async () => { const preview = await app().request("/api/admin/grade-export/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ scope: "year_all_students", format: "csv" }) }); expect(preview.status).toBe(200); const response = await app().request("/api/admin/grade-export/download?token=snapshot-token-0123456789"); expect(response.status).toBe(200); expect(response.headers.get("content-type")).toContain("text/csv"); expect(response.headers.get("content-disposition")).toContain("filename*=UTF-8''"); expect(response.headers.get("cache-control")).toBe("no-store"); expect((await response.text()).startsWith("\uFEFF")).toBeTrue(); });
  it("returns a PDF attachment and sanitizes Browser Run failures", async () => { const response = await app().request("/api/admin/grade-export/pdf?token=snapshot-token-0123456789"); expect(response.status).toBe(200); expect(response.headers.get("content-type")).toContain("application/pdf"); expect(response.headers.get("content-disposition")).toContain(".pdf"); const failed = await app(admin, { ...gradeExportService, downloadPdf: async () => { throw new Error("browser quota detail"); } }).request("/api/admin/grade-export/pdf?token=snapshot-token-0123456789"); expect(failed.status).toBe(500); expect(JSON.stringify(await failed.json())).not.toContain("browser quota detail"); });
  it("maps Browser Run saturation to a sanitized 503 and safe Retry-After", async () => { const response = await app(admin, { ...gradeExportService, downloadPdf: async () => { throw new PdfExportUnavailableError("30"); } }).request("/api/admin/grade-export/pdf?token=snapshot-token-0123456789"); expect(response.status).toBe(503); expect(response.headers.get("retry-after")).toBe("30"); expect(JSON.stringify(await response.json())).not.toContain("Browser Run"); });
  it("maps an unexpected download error to a safe 500 response", async () => { const secret = "export-internal-detail"; const response = await app(admin, { ...gradeExportService, download: async () => { throw new Error(secret); } }).request("/api/admin/grade-export/download?token=snapshot-token-0123456789"); expect(response.status).toBe(500); const result = await response.json(); expect(result).toMatchObject({ error: { code: "INTERNAL_ERROR" } }); expect(JSON.stringify(result)).not.toContain(secret); });
});
