import { Hono } from "hono";
import { validator } from "hono/validator";
import { requireAuthenticatedUser, requirePasswordChanged, requireRole, type AuthVariables, type SessionReader } from "../authorization";
import { respondAdminRouteError } from "./route-errors";
import { AdminDomainError } from "./service";
import { exportScopes, type GradeExportQuery, type GradeExportService } from "./grade-export";

const fail = (c: Parameters<typeof respondAdminRouteError>[0], error: unknown) => respondAdminRouteError(c, error, "grade_export");
const one = (value: string | string[] | undefined) => { if (Array.isArray(value)) throw new AdminDomainError("INVALID_EXPORT_QUERY", "出力条件を正しく指定してください。"); return value; };
const integer = (value: string | undefined, name: string) => { if (value === undefined) return undefined; if (!/^\d+$/.test(value)) throw new AdminDomainError("INVALID_EXPORT_QUERY", `${name}を正しく指定してください。`); return Number(value); };
const gradeScope = (value: unknown): GradeExportQuery["scope"] => { if (typeof value !== "string" || !exportScopes.includes(value as GradeExportQuery["scope"])) throw new AdminDomainError("INVALID_EXPORT_SCOPE", "出力パターンを正しく指定してください。"); return value as GradeExportQuery["scope"]; };
const queryObject = (value: unknown): GradeExportQuery => { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new AdminDomainError("INVALID_EXPORT_QUERY", "出力条件を正しく指定してください。"); const item = value as Record<string, unknown>; const optionalInteger = (raw: unknown, label: string) => raw === undefined ? undefined : typeof raw === "number" && Number.isInteger(raw) ? raw : (() => { throw new AdminDomainError("INVALID_EXPORT_QUERY", `${label}を正しく指定してください。`); })(); const optionalText = (raw: unknown) => raw === undefined ? undefined : typeof raw === "string" ? raw : (() => { throw new AdminDomainError("INVALID_EXPORT_QUERY", "出力条件を正しく指定してください。"); })(); const term = optionalInteger(item.term, "学期"); const gradeLevel = optionalInteger(item.gradeLevel, "学年"); if (term !== undefined && term !== 1 && term !== 2) throw new AdminDomainError("INVALID_EXPORT_TERM", "学期を正しく指定してください。"); if (gradeLevel !== undefined && gradeLevel !== 1 && gradeLevel !== 2 && gradeLevel !== 3) throw new AdminDomainError("INVALID_GRADE_LEVEL", "学年を正しく指定してください。"); return { scope: gradeScope(item.scope), academicYear: optionalInteger(item.academicYear, "年度"), term, gradeLevel, courseId: optionalText(item.courseId), subjectId: optionalText(item.subjectId) }; };
const exportQuery = validator("query", (value, c): GradeExportQuery | Response => { try { const scope = one(value.scope); if (!scope) throw new AdminDomainError("INVALID_EXPORT_SCOPE", "出力パターンを正しく指定してください。"); const term = integer(one(value.term), "学期"); const gradeLevel = integer(one(value.gradeLevel), "学年"); return queryObject({ scope, academicYear: integer(one(value.academicYear), "年度"), term, gradeLevel, courseId: one(value.courseId), subjectId: one(value.subjectId) }); } catch (error) { return fail(c, error); } });
const guarded = (reader: SessionReader) => [requireAuthenticatedUser(reader), requirePasswordChanged, requireRole("admin")] as const;
const encodedFilename = (filename: string) => encodeURIComponent(filename);
export const createGradeExportRoutes = (service: GradeExportService, reader: SessionReader) => new Hono<{ Variables: AuthVariables }>()
  .post("/admin/grade-export/preview", ...guarded(reader), validator("json", (value, c) => { try { return queryObject(value); } catch (error) { return fail(c, error); } }), async (c) => { try { return c.json(await service.preview(c.get("authUser").id, c.req.valid("json")), 200); } catch (error) { return fail(c, error); } })
  .get("/admin/grade-export/download", ...guarded(reader), validator("query", (value, c) => { try { const token = one(value.token); if (!token) throw new AdminDomainError("INVALID_EXPORT_TOKEN", "出力確認が期限切れです。もう一度件数を確認してください。"); return { token }; } catch (error) { return fail(c, error); } }), async (c) => { try { const file = await service.download(c.get("authUser").id, c.req.valid("query").token); return c.body(file.csv, 200, { "Content-Type": "text/csv; charset=utf-8", "Content-Disposition": `attachment; filename*=UTF-8''${encodedFilename(file.filename)}`, "Cache-Control": "no-store" }); } catch (error) { return fail(c, error); } });
