import { Database } from "bun:sqlite";
import { describe, expect, it } from "bun:test";
import { D1GradeExportService } from "./grade-export";
import { D1AuditService } from "./audit";

type Bound = { bind(...values: unknown[]): Bound; first<T>(): Promise<T | null>; all<T>(): Promise<{ results: T[] }>; run(): Promise<{ meta: { changes: number } }> };
const adapter = (database: Database) => ({ prepare(query: string) { const build = (values: unknown[]): Bound => { const statement = database.query(query) as unknown as { get(...v: unknown[]): unknown; all(...v: unknown[]): unknown; run(...v: unknown[]): { changes: number } }; return { bind: (...next) => build(next), first: async <T>() => statement.get(...values) as T | null, all: async <T>() => ({ results: statement.all(...values) as T[] }), run: async () => ({ meta: { changes: statement.run(...values).changes } }) }; }; return build([]); }, async batch(statements: Bound[]) { database.exec("BEGIN"); try { const result = []; for (const statement of statements) result.push(await statement.run()); database.exec("COMMIT"); return result; } catch (error) { database.exec("ROLLBACK"); throw error; } } }) as unknown as D1Database;
const setup = () => { const database = new Database(":memory:"); database.exec(`PRAGMA foreign_keys=ON;
 CREATE TABLE user(id text primary key,name text,email text,role text,status text); CREATE TABLE academic_years(year integer primary key,is_current integer); CREATE TABLE courses(id text primary key,name text); CREATE TABLE students(id text primary key,student_number text,name text,course_id text); CREATE TABLE subjects(id text primary key,academic_year integer,name text,grade_level integer); CREATE TABLE subject_term_statuses(subject_id text,term integer,is_finalized integer); CREATE TABLE grades(id text primary key,student_id text,subject_id text,academic_year integer,term integer,attempt integer not null default 1,attendance_rate integer,letter_grade text,unique(student_id,subject_id,term,attempt)); CREATE TABLE audit_logs(id text primary key,actor_user_id text references user(id),action text,entity_type text,entity_id text,academic_year integer,payload_json text,created_at integer default 0);
 CREATE TABLE grade_export_snapshots(id text primary key,owner_user_id text references user(id),academic_year integer,scope text not null default 'year_all_students',format text not null default 'csv',expires_at integer,claim_id text unique,claimed_at integer,created_at integer); CREATE TABLE grade_export_snapshot_rows(snapshot_id text references grade_export_snapshots(id) on delete cascade,position integer,student_number text,student_name text,academic_year integer,term integer,course_name text,grade_level integer,subject_name text,attendance_rate integer,letter_grade text,primary key(snapshot_id,position));
 INSERT INTO user VALUES ('admin','管理者','a','admin','active'),('teacher','講師','t','teacher','active'); INSERT INTO academic_years VALUES(2027,1); INSERT INTO courses VALUES('web','Web'); INSERT INTO students VALUES('s1','A-001','初期氏名','web'); INSERT INTO subjects VALUES('sub1',2027,'初期科目',1); INSERT INTO subject_term_statuses VALUES('sub1',1,1); INSERT INTO grades VALUES('g1','s1','sub1',2027,1,1,88,'A');`); let index = 0; const db = adapter(database); return { database, service: new D1GradeExportService(db, () => `snapshot-token-${++index}-0123456789`), d1: db }; };

describe("grade export snapshots (SQLite)", () => {
  it("materializes finalized values and remains exact after source state changes", async () => {
    const { database, service } = setup(); const preview = await service.preview("admin", { scope: "term", format: "csv", term: 1 }); expect(preview.rowCount).toBe(1); expect(database.query("SELECT attendance_rate FROM grade_export_snapshot_rows").get()).toEqual({ attendance_rate: 88 });
    database.exec("UPDATE grades SET attendance_rate=0,letter_grade='F'; UPDATE subject_term_statuses SET is_finalized=0; INSERT INTO subjects VALUES('sub2',2027,'新規科目',1); INSERT INTO subject_term_statuses VALUES('sub2',1,1); INSERT INTO grades VALUES('g2','s1','sub2',2027,1,1,100,'S')");
    const file = await service.download("admin", preview.token); expect(file.csv).toContain("初期科目"); expect(file.csv).toContain(",88,A"); expect(file.csv).not.toContain("新規科目"); expect(database.query("SELECT count(*) AS count FROM audit_logs WHERE action='grades_exported'").get()).toEqual({ count: 1 });
    const payload = String((database.query("SELECT payload_json FROM audit_logs").get() as { payload_json: string }).payload_json); expect(payload).not.toContain("初期氏名"); expect(payload).not.toContain(preview.token);
    await expect(service.download("admin", preview.token)).rejects.toMatchObject({ code: "EXPORT_SNAPSHOT_NOT_FOUND", status: 404 });
  });
  it("exports only the latest passing retake for a failed original attempt", async () => {
    const { database, service } = setup();
    database.exec("UPDATE grades SET letter_grade='F',attendance_rate=50,attempt=1 WHERE id='g1'; INSERT INTO grades VALUES('g2','s1','sub1',2027,1,2,80,'B')");
    const preview = await service.preview("admin", { scope: "term", format: "csv", term: 1 });
    expect(preview.rowCount).toBe(1);
    expect(database.query("SELECT attendance_rate,letter_grade FROM grade_export_snapshot_rows").get()).toEqual({ attendance_rate: 80, letter_grade: "B" });
    const file = await service.download("admin", preview.token);
    expect(file.csv).toContain(",80,B");
    expect(file.csv).not.toContain(",50,F");
  });
  it("binds snapshots to owner and exposes grade_export audit filtering", async () => {
    const { service, d1 } = setup(); const preview = await service.preview("admin", { scope: "year_all_students", format: "csv" }); await expect(service.download("teacher", preview.token)).rejects.toMatchObject({ code: "EXPORT_SNAPSHOT_NOT_FOUND", status: 404 }); await service.download("admin", preview.token);
    const audit = await new D1AuditService(d1).logs({ limit: 20, targetType: "grade_export" }); expect(audit.items).toHaveLength(1); expect(audit.items[0]?.targetType).toBe("grade_export"); expect(audit.items[0]?.summary).toBe("成績CSVを出力");
  });
  it("rejects expired snapshots with 410 and creates separate tokens for changed filters", async () => {
    const { database, service } = setup(); const first = await service.preview("admin", { scope: "year_all_students", format: "csv" }); const filtered = await service.preview("admin", { scope: "year_all_students", format: "csv", gradeLevel: 1 }); expect(filtered.token).not.toBe(first.token);
    database.exec(`UPDATE grade_export_snapshots SET expires_at=0 WHERE id='${first.token}'`);
    await expect(service.download("admin", first.token)).rejects.toMatchObject({ code: "EXPORT_SNAPSHOT_EXPIRED", status: 410 });
  });
  it("rejects over 10,000 rows atomically without a snapshot or audit", async () => {
    const { database, service } = setup(); database.exec("WITH RECURSIVE n(x) AS (SELECT 2 UNION ALL SELECT x+1 FROM n WHERE x<=10001) INSERT INTO students SELECT 'many-student-'||x,'M'||x,'学生'||x,'web' FROM n; WITH RECURSIVE n(x) AS (SELECT 2 UNION ALL SELECT x+1 FROM n WHERE x<=10001) INSERT INTO grades SELECT 'many'||x,'many-student-'||x,'sub1',2027,1,1,88,'A' FROM n");
    await expect(service.preview("admin", { scope: "year_all_students", format: "csv" })).rejects.toThrow(); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 0 }); expect(database.query("SELECT count(*) AS count FROM audit_logs").get()).toEqual({ count: 0 });
  });
  it("cleans snapshot and writes no audit when generated CSV exceeds 5MB", async () => {
    const { database, service } = setup(); database.exec("UPDATE students SET name=printf('%1000s','x') WHERE id='s1'; WITH RECURSIVE n(x) AS (SELECT 2 UNION ALL SELECT x+1 FROM n WHERE x<=6000) INSERT INTO students SELECT 'large-student-'||x,'L'||x,printf('%1000s','x'),'web' FROM n; WITH RECURSIVE n(x) AS (SELECT 2 UNION ALL SELECT x+1 FROM n WHERE x<=6000) INSERT INTO grades SELECT 'large'||x,'large-student-'||x,'sub1',2027,1,1,88,'A' FROM n");
    const preview = await service.preview("admin", { scope: "year_all_students", format: "csv" }); expect(preview.rowCount).toBeGreaterThan(5_000); await expect(service.download("admin", preview.token)).rejects.toMatchObject({ code: "EXPORT_TOO_LARGE", status: 413 }); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 0 }); expect(database.query("SELECT count(*) AS count FROM audit_logs").get()).toEqual({ count: 0 });
  });
  it("atomically allows exactly one concurrent token consumer and records one audit", async () => {
    const { database, service } = setup(); const preview = await service.preview("admin", { scope: "year_all_students", format: "csv" }); const results = await Promise.allSettled([service.download("admin", preview.token), service.download("admin", preview.token)]); expect(results.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(results.filter((result) => result.status === "rejected")).toHaveLength(1); const rejected = results.find((result): result is PromiseRejectedResult => result.status === "rejected"); expect(rejected?.reason).toMatchObject({ code: "EXPORT_SNAPSHOT_EXPIRED", status: 410 }); expect(database.query("SELECT count(*) AS count FROM audit_logs WHERE action='grades_exported'").get()).toEqual({ count: 1 }); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 0 });
  });
  it("renders one immutable PDF through Browser Run, then writes the distinct audit", async () => {
    const { database, d1 } = setup(); let html = ""; const service = new D1GradeExportService(d1, () => "pdf-token-0123456789", () => new Date("2027-04-01T00:00:00Z"), { quickAction: async (_action, options) => { html = "html" in options ? options.html : ""; return new Response(Uint8Array.from([37, 80, 68, 70]), { headers: { "Content-Type": "application/pdf" } }); } });
    const preview = await service.preview("admin", { scope: "term", format: "pdf", term: 1 }); const file = await service.downloadPdf("admin", preview.token);
    expect(Array.from(new Uint8Array(file.pdf))).toEqual([37, 80, 68, 70]); expect(html).toContain("年度・学期別"); expect(database.query("SELECT count(*) AS count FROM audit_logs WHERE action='grades_pdf_exported'").get()).toEqual({ count: 1 }); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 0 });
  });
  it("cleans the claimed snapshot and writes no audit when Browser Run rejects", async () => {
    const { database, d1 } = setup(); const service = new D1GradeExportService(d1, () => "pdf-error-token-0123456789", () => new Date("2027-04-01T00:00:00Z"), { quickAction: async () => { throw new Error("quota"); } });
    const preview = await service.preview("admin", { scope: "year_all_students", format: "pdf" }); await expect(service.downloadPdf("admin", preview.token)).rejects.toMatchObject({ code: "PDF_EXPORT_UNAVAILABLE", status: 503 }); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 0 }); expect(database.query("SELECT count(*) AS count FROM audit_logs").get()).toEqual({ count: 0 });
  });
  it("rejects every invalid Browser Run response without auditing and forwards only a safe 429 retry delay", async () => {
    const cases = [new Response("busy", { status: 429, headers: { "Content-Type": "application/json", "Retry-After": "30" } }), new Response("upstream", { status: 500, headers: { "Content-Type": "application/json" } }), new Response("not pdf", { headers: { "Content-Type": "text/plain" } }), new Response(null, { headers: { "Content-Type": "application/pdf" } })];
    let index = 0; for (const response of cases) { const { database, d1 } = setup(); const service = new D1GradeExportService(d1, () => `pdf-response-${++index}-0123456789`, () => new Date("2027-04-01T00:00:00Z"), { quickAction: async () => response.clone() }); const preview = await service.preview("admin", { scope: "year_all_students", format: "pdf" }); await expect(service.downloadPdf("admin", preview.token)).rejects.toMatchObject({ code: "PDF_EXPORT_UNAVAILABLE", status: 503, ...(response.status === 429 ? { retryAfter: "30" } : {}) }); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 0 }); expect(database.query("SELECT count(*) AS count FROM audit_logs").get()).toEqual({ count: 0 }); }
  });
  it("does not consume a token from the other format, then consumes the matching format once", async () => {
    const { database, d1 } = setup(); const browser = { quickAction: async () => new Response(Uint8Array.from([37, 80, 68, 70]), { headers: { "Content-Type": "application/pdf" } }) }; let index = 0; const service = new D1GradeExportService(d1, () => `cross-format-${++index}-0123456789`, () => new Date("2027-04-01T00:00:00Z"), browser);
    const csv = await service.preview("admin", { scope: "year_all_students", format: "csv" }); await expect(service.downloadPdf("admin", csv.token)).rejects.toMatchObject({ code: "EXPORT_FORMAT_MISMATCH", status: 409 }); expect(database.query("SELECT count(*) AS count FROM grade_export_snapshots").get()).toEqual({ count: 1 }); await service.download("admin", csv.token); const pdf = await service.preview("admin", { scope: "year_all_students", format: "pdf" }); await expect(service.download("admin", pdf.token)).rejects.toMatchObject({ code: "EXPORT_FORMAT_MISMATCH", status: 409 }); await service.downloadPdf("admin", pdf.token); expect(database.query("SELECT action FROM audit_logs ORDER BY action").all()).toEqual([{ action: "grades_exported" }, { action: "grades_pdf_exported" }]);
  });
});
